[2024-10-17T07:37:05.132+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-17T07:37:05.432+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_cricket_stats.run_script scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T07:37:05.530+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_cricket_stats.run_script scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T07:37:05.536+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-17T07:37:05.700+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_script> on 2024-10-16 00:00:00+00:00
[2024-10-17T07:37:05.920+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=90) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-17T07:37:06.059+0000] {standard_task_runner.py:72} INFO - Started process 109 to run task
[2024-10-17T07:37:06.164+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_cricket_stats', 'run_script', 'scheduled__2024-10-16T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_extract_push_gcs.py', '--cfg-path', '/tmp/tmpfvnvdo3g']
[2024-10-17T07:37:06.179+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask run_script
[2024-10-17T07:37:07.118+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_cricket_stats.run_script scheduled__2024-10-16T00:00:00+00:00 [running]> on host e76a770c8a72
[2024-10-17T07:37:07.803+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='akhilmacha996646@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_cricket_stats' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-16T00:00:00+00:00'
[2024-10-17T07:37:07.813+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-17T07:37:07.815+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-17T07:37:07.818+0000] {logging_mixin.py:190} INFO - Current task name:run_script state:running start_date:2024-10-17 07:37:05.435213+00:00
[2024-10-17T07:37:07.823+0000] {logging_mixin.py:190} INFO - Dag name:fetch_cricket_stats and current dag run status:running
[2024-10-17T07:37:07.826+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-17T07:37:07.844+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-17T07:37:07.851+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'C:\\Users\\sandh\\OneDrive\\Documents\\akhil_projects\\AIRFLOW_project\\dags\\extract_and_push_gcs.py']
[2024-10-17T07:37:07.949+0000] {subprocess.py:86} INFO - Output:
[2024-10-17T07:37:07.983+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: C:UserssandhOneDriveDocumentsakhil_projectsAIRFLOW_projectdagsextract_and_push_gcs.py: command not found
[2024-10-17T07:37:07.989+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-10-17T07:37:08.085+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-10-17T07:37:08.199+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-17T07:37:08.205+0000] {logging_mixin.py:190} INFO - Task start:2024-10-17 07:37:05.435213+00:00 end:2024-10-17 07:37:08.181404+00:00 duration:2.746191
[2024-10-17T07:37:08.211+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): run_script> dag:<DAG: fetch_cricket_stats> dagrun:<DagRun fetch_cricket_stats @ 2024-10-16 00:00:00+00:00: scheduled__2024-10-16T00:00:00+00:00, state:running, queued_at: 2024-10-17 07:21:50.543384+00:00. externally triggered: False>
[2024-10-17T07:37:08.214+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 127.
[2024-10-17T07:37:08.217+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_cricket_stats, task_id=run_script, run_id=scheduled__2024-10-16T00:00:00+00:00, execution_date=20241016T000000, start_date=20241017T073705, end_date=20241017T073708
[2024-10-17T07:37:08.372+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-17T07:37:08.380+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task run_script (Bash command failed. The command returned a non-zero exit code 127.; 109)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-10-17T07:37:08.498+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-17T07:37:08.601+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-17T07:37:08.620+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
